version: '2.0'

services:
  postgres_db:
    image: postgres:latest
    networks:
      new:
        aliases:
          - database
    container_name: expected_move_psql
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./migrations:/migrations
    command: ["-v", "/Users/dallincoons/go/src/expected_move/migrations:/migrations", "--network", "host", "migrate/migrate", "-path", "/migrations/", "-database", "postgresql://root:secret@localhost:5432/expected_move?sslmode=disable", "up"]
    links:
      - postgres_db
networks:
  new:
