version: '2.0'

services:
  expected_move_scheduler:
    build: .
    container_name: expected_move_scheduler
    command: ["./main", "scheduleExpectedMoves"]
  prices_scheduler:
    build: .
    container_name: prices_scheduler
    command: ["./main", "schedulePrices"]
    env_file:
      - ./.env
  postgres_db:
    image: postgres:latest
    container_name: expected_move_psql
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
