version: '2.0'

services:
  postgres_db:
    image: postgres:latest
    networks:
      host:
        aliases:
          - database
    container_name: expected_move_psql
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
networks:
  host:
