version: '2.0'

services:
  app:
    build: .
    container_name: expected_move_backend
  postgres_db:
    image: postgres:latest
    container_name: expected_move_psql
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
